// error: 2

fn main() -> int {
  return 2;
}
