//= error exception

fun main() {
    do {
        throwFromNativeButNotThrows(true);
    } catch e: Exception {
        assert(false);
    }
}